# Generated by Django 5.0.6 on 2024-07-29 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='article_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('img', models.ImageField(default='"https://via.placeholder.com/300x200"', upload_to='images/article')),
                ('date', models.DateField()),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_Area.author')),
            ],
        ),
    ]
