# Generated by Django 5.1 on 2024-10-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default=True, max_length=40, null=True)),
                ('password', models.CharField(default=True, max_length=40, null=True)),
            ],
        ),
    ]
