# Generated by Django 5.1 on 2024-09-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='dis',
            field=models.CharField(default=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
