# Generated by Django 5.1 on 2024-12-09 13:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_myuser_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='clinet_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weigth', models.FloatField()),
                ('fate', models.FloatField(help_text='Please enter a value between 1 and 10.', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)])),
                ('milk_category', models.CharField(choices=[('Cow', 'Buffalo')], default='Buffalo', help_text='Select the type of Milk', max_length=20)),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
