# Generated by Django 5.1 on 2024-12-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_clinet_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinet_data',
            name='milk_category',
            field=models.CharField(choices=[('Cow', 'Buffalo')], default='Cow', help_text='Select the type of Milk', max_length=20),
        ),
    ]
