# Generated by Django 5.1 on 2024-12-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_clinet_data_milk_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinet_data',
            name='milk_category',
            field=models.CharField(choices=[('Cow', 'Cow'), ('Buffalo', 'Buffalo')], help_text='Select the type of Milk', max_length=20),
        ),
    ]
