# Generated by Django 5.0.6 on 2024-08-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_post', '0002_user_post_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/Uploads/'),
        ),
    ]
