# Generated by Django 5.1 on 2024-10-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycustomeuser',
            name='username',
        ),
    ]
