# Generated by Django 5.1 on 2024-10-31 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custuser', '0003_trackermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackermodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
